version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8081:80

  servidor1:
    build: 
      context: ./servidor1
      dockerfile: Dockerfile
    container_name: servidor1
    ports:
      - 5001:5000
  
  servidor2:
    build: 
      context: ./servidor2
      dockerfile: Dockerfile
    container_name: servidor2
    ports:
      - 5002:5000

  servidor3:
    build: 
      context: ./servidor3
      dockerfile: Dockerfile
    container_name: servidor3
    ports:
      - 5003:5000

  locust:
    image: locustio/locust:latest
    container_name: locust
    ports:
      - 8089:8089
    volumes:
      - C:\Users\APP DISTRIBUIDAS\Desktop\rendimiento:/mnt/locust
    command: ["-f","/mnt/locust/locustfile.py"]

